### ISSUE TITLE
Python3 roadmap

### ISSUE THREAD

**Issue by brennv** [linkedin/luminol#22]
Continuing the discussion from #15. I think adding travis and getting tests passing would good start. That way we can watch follow-on PRs pass or fail.

- [x] ~~fix tests~~  #20 
- [x] ~~add travis~~  #11 
- [x] ~~fix spacing~~  #25
- [x] ~~clean up~~  #27 
- [x] ~~add Python 3 support~~  #28
- [x] ~~maybe more pep8 fun~~ #29 and/or refactor tests
- [x] ~~update readme~~ #30 ~~and bump version~~ #31
- [ ] pypi release

**Comment by brennv** [comment]
For clean up I've got #27 ready to go with cleaned up spacing for tests/. Was there anything else you'd like to do specific to 2.7?

**Comment by brennv** [comment]
On considering whether or not to refactor tests, the current file structure is:
```
.
./demo
./src
./src/luminol
./src/luminol/algorithms
./src/luminol/modules
./src/luminol/tests
```

Conventionally for Python it would be:
```
.
./demo
./luminol
./luminol/algorithms
./luminol/modules
./tests
```

The advantage being that tests could be extended to include tests of `/demo` work.

**Comment by brennv** [comment]
Closing due to age
